# Generated by Django 4.2.7 on 2025-02-23 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='stock_market_dashboard/static/avatars/'),
        ),
    ]
